### ISSUE TITLE
Error when generating a new app with @ng-rspack/nx:app

### ISSUE THREAD

**Issue by eilensm** [Coly010/ng-rspack-build#31]
when executing the command to generate a new app, I get an error (see below). I'm running Windows 64-bit.

`**
$ npx nx g @ng-rspack/nx:app apps/myapp --verbose

 NX   Unable to resolve @ng-rspack/nx:app.

Cannot find module './src/generators/application/schema.json'
Require stack:
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\config\schema-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\command-line\run\executor-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\devkit-internals.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\assert-workspace-validity.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\build-project-graph.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\project-graph.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\file-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\package-manager.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\package-json.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\bin\nx.js
Error: Unable to resolve @ng-rspack/nx:app.
Cannot find module './src/generators/application/schema.json'
Require stack:
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\config\schema-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\command-line\run\executor-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\devkit-internals.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\assert-workspace-validity.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\build-project-graph.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\project-graph.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\project-graph\file-utils.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\package-manager.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\package-json.js
- C:\workspaces\rspack\ng-rspack-test\node_modules\nx\bin\nx.js
    at getGeneratorInformation (C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\command-line\generate\generator-utils.js:40:15)
    at C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\command-line\generate\generate.js:216:248
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleErrors (C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\utils\handle-errors.js:8:24)
    at async Object.handler (C:\workspaces\rspack\ng-rspack-test\node_modules\nx\src\command-line\generate\command-object.js:13:22)
**`

**Comment by dirk122119** [comment]
I also run into this error, Do you have any resolution?

**Comment by eilensm** [comment]
No. But didn't try it out lately since I switched to rsbuild which was quite easy to integrate in my current app.

**Comment by skoblenick** [comment]
Created repo that reproduces the issue: https://github.com/skoblenick/ng-rspack-build-testing/tree/issue-31

**Comment by skoblenick** [comment]
looking at the src in the node_modules directory, the `schemaPath` arg is being set relative to `./src/generators/application/schema.json` and later it's being joined with `<working_dir>/node_modules/@ng-rspack/nx` but there is **no** `src` directory within the node_module; it should probably be `dist`

**Comment by skoblenick** [comment]
if I pull the `schema.json` from the [nx-plugin](https://github.com/Coly010/ng-rspack-build/blob/main/packages/nx-plugin/src/generators/application/schema.json) src into the expected path, the generator will run but fails cause the path to the `"./src/generators/application/application"` isn't correct and is in the dist folder.

FYI: this issue also happens with the `host` and and `remote` generators as well

**Comment by dennisroche** [comment]
In [59daf98](https://github.com/Coly010/ng-rspack-build/commit/59daf9845b12b95aedeb76c483b11fa81fd93fad) the `packages/nx-plugin/project.json` build targets were changed to not include the `src/` folder removing:

```json
"build": {
      "executor": "@nx/js:swc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/nx",
        "main": "packages/nx-plugin/src/index.ts",
        "tsConfig": "packages/nx-plugin/tsconfig.lib.json",
        "assets": [
          "packages/nx-plugin/*.md",
          {
            "input": "./packages/nx-plugin/src",
            "glob": "**/!(*.ts)",
            "output": "./src"
          },
          {
            "input": "./packages/nx-plugin/src",
            "glob": "**/*.d.ts",
            "output": "./src"
          },
          {
            "input": "./packages/nx-plugin",
            "glob": "generators.json",
            "output": "."
          },
          {
            "input": "./packages/nx-plugin",
            "glob": "executors.json",
            "output": "."
          }
        ]
      }
    },
```

This was part of `feat(build): add rsbuild plugin` so likely intentional but it might need some changes to the parent build to still include the `schema.json` files.

**Comment by dennisroche** [comment]
I created a patch using `yarn patch` with the missing `schema.json` and `schema.t.ds` files and updated the paths to use `dist/`.

**Comment by zargham-leanix** [comment]
@Coly010 `npx nx g @ng-rspack/nx:app` is not working anymore, could you help look into it?
