### ISSUE TITLE
Runtime problem "JIT compilation failed..." when providing services from (3rd party) npm libraries (e.g. transloco)

### ISSUE THREAD

**Issue by eilensm** [Coly010/ng-rspack-build#32]
I got an error in the browser when serving my project using "rsbuild dev". I reproduced the issue in the apps/rsbuild/csr/css  sample project by integrating transloco as described here (https://jsverse.github.io/transloco/docs/getting-started/installation).

One thing to mention is, that I installed transloco with "--legacy-peer-deps" due to a conflicting peer dependency with "chokidar" library.

The error message is:
```
JIT compilation failed for injectable class DefaultTranspiler {
    config = (0,_angular_core__WEBPACK_IMPORTED_MODULE_1__.inject)(TRANSLOCO_CONFIG, { optional: true }) ?? defaultConfig;
    get interpolationMatcher() {
        return resolveM…
```

```
Uncaught Error: The injectable 'DefaultTranspiler' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.

The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.

Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.mjs:2524:1)
    at Module.ɵɵngDeclareFactory (core.mjs:38883:1)
    at <static_initializer> (jsverse-transloco.mjs:281:1)
    at ../../../../node_modules/@jsverse/transloco/fesm2022/jsverse-transloco.mjs (jsverse-transloco.mjs:189:1)
    at __webpack_require__ (main.ts:5:1)
    at fn (main.ts:5:1)
    at ./src/app/app.config.ts (app.component.ts:11:1)
    at __webpack_require__ (main.ts:5:1)
    at fn (main.ts:5:1)
    at ./src/main.ts (transloco-loader.ts:5:1)
```

![image](https://github.com/user-attachments/assets/5b93acfd-7162-40c0-a4c9-8e9f569c507f)

**Comment by Coly010** [comment]
Oh I know why this is.

I was hoping this wouldn’t be the case but I was trying to limit the amount of pre-processing that needed to be done during build on npm packages to just `@angular/*` packages. 

It looks like I’ll need to expand that to either find packages using `@angular` or just all npm packages.

I’d rather not do the latter, as it will increase build time.

**Comment by eilensm** [comment]
Yes, this version works! Thanks a lot! Btw, you're doing a really nice job!

**Comment by eilensm** [comment]
Maybe there is some other issue with JSNLog (https://jsnlog.com/). When trying to access the JSNLog object, I get the following error message:

```
ERROR TypeError: (0 , jsnlog__WEBPACK_IMPORTED_MODULE_1__.JL) is not a function
    at new AppComponent (app.component.ts:17:1)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:12:1)
    at getNodeInjectable (core.mjs:5287:1)
    at createRootComponent (core.mjs:17524:1)
    at ComponentFactory.create (core.mjs:17380:1)
    at ApplicationRef.bootstrap (core.mjs:22748:1)
    at core.mjs:34735:1
    at _ZoneDelegate.invoke (zone.js:369:1)
    at Object.onInvoke (core.mjs:6495:1)
    at _ZoneDelegate.invoke (zone.js:368:1)
```

I added the code to the app.component.ts like this. Any ideas?

```
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NxWelcomeComponent } from './nx-welcome.component';
import { JL } from "jsnlog";

@Component({
  imports: [NxWelcomeComponent, RouterModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'rsbuild-csr-css';

  constructor() {
    JL().info('>>>App started');
  }
}
```

**Comment by Coly010** [comment]
I'm going to open a different issue for jsnlog. 

It's behaving extremely strangely and could be related to how it is packaged.
