### ISSUE TITLE
Issue with JSNLog - not a function

### ISSUE THREAD

**Issue by Coly010** [Coly010/ng-rspack-build#33]
Maybe there is some other issue with JSNLog (https://jsnlog.com/). When trying to access the JSNLog object, I get the following error message:

```
ERROR TypeError: (0 , jsnlog__WEBPACK_IMPORTED_MODULE_1__.JL) is not a function
    at new AppComponent (app.component.ts:17:1)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:12:1)
    at getNodeInjectable (core.mjs:5287:1)
    at createRootComponent (core.mjs:17524:1)
    at ComponentFactory.create (core.mjs:17380:1)
    at ApplicationRef.bootstrap (core.mjs:22748:1)
    at core.mjs:34735:1
    at _ZoneDelegate.invoke (zone.js:369:1)
    at Object.onInvoke (core.mjs:6495:1)
    at _ZoneDelegate.invoke (zone.js:368:1)
```

I added the code to the app.component.ts like this. Any ideas?

```
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NxWelcomeComponent } from './nx-welcome.component';
import { JL } from "jsnlog";

@Component({
  imports: [NxWelcomeComponent, RouterModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'rsbuild-csr-css';

  constructor() {
    JL().info('>>>App started');
  }
}
```

_Originally posted by @eilensm in https://github.com/Coly010/ng-rspack-build/issues/32#issuecomment-2566590437_

**Comment by Coly010** [comment]
It's happening because the `jsnlog` package ships a `.ts` file in its package. Rsbuild is currently resolving that .ts file instead of the .js file

**Comment by eilensm** [comment]
Great that you already found the reason for this issue! I'm going offline for today. Have a nice evening and a happy New Year!!!

**Comment by Coly010** [comment]
Fixed in version 19.0.0-alpha.10
